#!/usr/bin/env groovy
pipeline {
  agent {
    docker {
      label 'docker && !gevrey'
      image 'node:8.9'
    }
  }
  environment {
    CLIENT = 'atolcd'
    PROJECT = 'onlyoffice-lib'
    VERSION = sh (
        script: 'git describe --always',
        returnStdout: true
      ).trim()
  }
  stages {
    stage('Build') {
      steps {
        dir(env.PROJECT) {
          sh 'npm install'
          sh 'npm run build:jenkins'
        }
      }
    }
  }
  post {
    success {
      dir(env.PROJECT) {

      }
    }
    cleanup {
       sh "git checkout -- ."
    }
  }
}
